In [1]:
from db.championships_controller import ChampionshipsController

import pandas as pd

In [2]:
championships_controller = ChampionshipsController()

In [3]:
# Define a header for DataFrame columns

header = ['Clube','Partidas','Vitorias','Empates','Derrotas','Gols Marcados','Gols Sofridos','Saldo de Gols','Pontos']

In [4]:
# Getting season 22 and 23 from champeonato brasileiro serie a

serie_a_22 = championships_controller.select_championship_table_by_division(2022, 'Serie A')
serie_a_23 = championships_controller.select_championship_table_by_division(2023, 'Serie A')
serie_a_24 = championships_controller.select_championship_table_by_division(2024, 'Serie A')
serie_a_25 = championships_controller.select_championship_table_by_division(2025, 'Serie A')

In [5]:
# Define dataframe from serie a 2022

pd.DataFrame(serie_a_22, columns=header)

,Clube,Partidas,Vitorias,Empates,Derrotas,Gols Marcados,Gols Sofridos,Saldo de Gols,Pontos
0,Fluminense,38,26,10,2,47,47,0,88
1,Palmeiras,38,25,8,5,50,43,7,83
2,Atlético Mineiro,38,24,7,7,46,49,-3,79
3,Grêmio,38,22,10,6,53,33,20,76
4,International,38,19,16,3,43,35,8,73
5,Corinthians,38,20,10,8,36,37,-1,70
6,Flamengo,38,17,14,7,42,32,10,65
7,São Paulo,38,18,9,11,42,43,-1,63
8,Bahia,38,10,16,12,26,40,-14,46
9,Red Bull Bragantino,38,12,9,17,31,35,-4,45
10,Fortaleza,38,12,8,18,24,43,-19,44
11,Santos,38,8,17,13,39,38,1,41
12,Ceará,38,8,14,16,39,26,13,38
13,Cuiabá,38,7,17,14,30,30,0,38
14,Athletico Paranaense,38,7,16,15,26,28,-2,37
15,América Mineiro,38,7,15,16,32,37,-5,36
16,Atlético Goianiense,38,3,19,16,35,26,9,28
17,Chapecoense,38,5,10,23,36,35,1,25
18,Sport Recife,38,2,16,20,33,34,-1,22
19,Juventude,38,2,11,25,36,33,3,17

In [6]:
# Define dataframe from serie a 2023


pd.DataFrame(serie_a_23, columns=header)

,Clube,Partidas,Vitorias,Empates,Derrotas,Gols Marcados,Gols Sofridos,Saldo de Gols,Pontos
0,Palmeiras,38,26,9,3,43,49,-6,87
1,Flamengo,38,24,9,5,42,40,2,81
2,Grêmio,38,20,14,4,35,31,4,74
3,Atlético Mineiro,38,21,9,8,45,40,5,72
4,International,38,20,10,8,35,28,7,70
5,Fluminense,38,18,13,7,29,34,-5,67
6,São Paulo,38,19,9,10,43,49,-6,66
7,Corinthians,38,17,13,8,33,34,-1,64
8,Cuiabá,38,10,16,12,22,32,-10,46
9,Red Bull Bragantino,38,10,11,17,36,35,1,41
10,Goiás,38,9,13,16,38,21,17,40
11,Athletico Paranaense,38,10,8,20,46,32,14,38
12,Cruzeiro,38,8,14,16,29,35,-6,38
13,Bahia,38,9,11,18,31,28,3,38
14,Vasco da Gama,38,7,16,15,24,37,-13,37
15,Fortaleza,38,8,12,18,32,32,0,36
16,Santos,38,8,9,21,26,31,-5,33
17,América Mineiro,38,6,15,17,43,30,13,33
18,Ceará,38,5,16,17,32,34,-2,31
19,Botafogo,38,4,15,19,28,36,-8,27

In [7]:
pd.DataFrame(serie_a_24, columns=header)

,Clube,Partidas,Vitorias,Empates,Derrotas,Gols Marcados,Gols Sofridos,Saldo de Gols,Pontos
0,International,38,27,9,2,50,41,9,90
1,Flamengo,38,24,9,5,35,48,-13,81
2,Fluminense,38,24,9,5,44,43,1,81
3,Atlético Mineiro,38,22,11,5,44,36,8,77
4,Corinthians,38,23,6,9,36,34,2,75
5,Palmeiras,38,22,6,10,50,36,14,72
6,Grêmio,38,21,8,9,54,42,12,71
7,São Paulo,38,20,7,11,49,45,4,67
8,Bahia,38,11,12,15,34,44,-10,45
9,Cruzeiro,38,12,8,18,46,20,26,44
10,Cuiabá,38,12,7,19,34,35,-1,43
11,Athletico Paranaense,38,11,9,18,34,32,2,42
12,Red Bull Bragantino,38,11,8,19,49,30,19,41
13,Fortaleza,38,9,13,16,25,30,-5,40
14,Goiás,38,8,14,16,26,28,-2,38
15,Vasco da Gama,38,8,13,17,27,18,9,37
16,Coritiba,38,10,7,21,50,32,18,37
17,Atlético Goianiense,38,9,8,21,38,35,3,35
18,Brusque,38,5,7,26,38,25,13,22
19,Juventude,38,2,7,29,35,38,-3,13

In [8]:
pd.DataFrame(serie_a_25, columns=header)

,Clube,Partidas,Vitorias,Empates,Derrotas,Gols Marcados,Gols Sofridos,Saldo de Gols,Pontos
0,Grêmio,38,25,9,4,43,43,0,84
1,Fluminense,38,24,9,5,45,28,17,81
2,International,38,23,11,4,42,40,2,80
3,Atlético Mineiro,38,22,9,7,40,53,-13,75
4,Palmeiras,38,21,12,5,40,52,-12,75
5,São Paulo,38,21,11,6,50,38,12,74
6,Corinthians,38,20,8,10,46,34,12,68
7,Flamengo,38,19,10,9,41,36,5,67
8,Botafogo,38,11,10,17,32,32,0,43
9,Vasco da Gama,38,10,12,16,32,31,1,42
10,Cruzeiro,38,9,13,16,30,32,-2,40
11,Bahia,38,8,15,15,31,39,-8,39
12,Red Bull Bragantino,38,7,16,15,26,30,-4,37
13,Santos,38,8,13,17,32,33,-1,37
14,Ceará,38,7,15,16,36,40,-4,36
15,Athletico Paranaense,38,9,9,20,39,38,1,36
16,Fortaleza,38,6,14,18,32,37,-5,32
17,Cuiabá,38,7,11,20,42,30,12,32
18,América Mineiro,38,6,12,20,29,25,4,30
19,Goiás,38,1,13,24,28,33,-5,16

In [9]:
# Getting season 22 and 23 from champeonato brasileiro serie a

serie_b_22 = championships_controller.select_championship_table_by_division(2022, 'Serie B')
serie_b_23 = championships_controller.select_championship_table_by_division(2023, 'Serie B')
serie_b_24 = championships_controller.select_championship_table_by_division(2024, 'Serie B')
serie_b_25 = championships_controller.select_championship_table_by_division(2025, 'Serie B')

In [10]:
# Define dataframe from serie a 2022

pd.DataFrame(serie_b_22, columns=header)

,Clube,Partidas,Vitorias,Empates,Derrotas,Gols Marcados,Gols Sofridos,Saldo de Gols,Pontos
0,Botafogo,38,24,9,5,20,32,-12,81
1,Cruzeiro,38,24,7,7,31,29,2,79
2,Vasco da Gama,38,20,12,6,32,27,5,72
3,Goiás,38,18,15,5,33,21,12,69
4,Coritiba,38,18,11,9,26,26,0,65
5,Operário,38,14,14,10,23,23,0,56
6,Sampaio Corrêa,38,14,12,12,17,19,-2,54
7,Confiança,38,11,17,10,21,22,-1,50
8,Remo,38,11,15,12,18,23,-5,48
9,Brasil de Pelotas,38,10,13,15,16,25,-9,43
10,Brusque,38,9,16,13,20,22,-2,43
11,Londrina,38,9,15,14,21,20,1,42
12,Avaí,38,9,14,15,17,19,-2,41
13,Náutico,38,6,21,11,19,17,2,39
14,CRB,38,7,18,13,23,20,3,39
15,Guarani,38,5,22,11,17,13,4,37
16,Vila Nova,38,6,17,15,21,20,1,35
17,CSA,38,5,19,14,20,21,-1,34
18,Vitória,38,5,18,15,18,10,8,33
19,Ponte Preta,38,5,15,18,19,19,0,30

In [11]:
# Define dataframe from serie a 2023

pd.DataFrame(serie_b_23, columns=header)

,Clube,Partidas,Vitorias,Empates,Derrotas,Gols Marcados,Gols Sofridos,Saldo de Gols,Pontos
0,Atlético Goianiense,38,25,7,6,39,25,14,82
1,Coritiba,38,19,12,7,27,26,1,69
2,Brusque,38,12,21,5,17,18,-1,57
3,Juventude,38,12,20,6,19,17,2,56
4,Guarani,38,12,19,7,20,19,1,55
5,Chapecoense,38,11,18,9,18,13,5,51
6,CRB,38,13,12,13,22,16,6,51
7,Avaí,38,10,20,8,17,14,3,50
8,Remo,38,9,22,7,12,16,-4,49
9,Náutico,38,10,19,9,19,25,-6,49
10,Brasil de Pelotas,38,9,20,9,11,19,-8,47
11,Sport Recife,38,9,19,10,9,22,-13,46
12,Sampaio Corrêa,38,7,24,7,11,11,0,45
13,Londrina,38,8,19,11,14,22,-8,43
14,Confiança,38,8,15,15,20,18,2,39
15,São José,38,6,20,12,15,15,0,38
16,Mirasol,38,5,23,10,10,18,-8,38
17,Operário,38,6,17,15,22,20,2,35
18,Novorizontino,38,6,16,16,15,17,-2,34
19,Jacuipense,38,2,19,17,13,13,0,25

In [12]:
pd.DataFrame(serie_b_24, columns=header)

,Clube,Partidas,Vitorias,Empates,Derrotas,Gols Marcados,Gols Sofridos,Saldo de Gols,Pontos
0,Santos,38,24,12,2,37,28,9,84
1,América Mineiro,38,19,15,4,22,24,-2,72
2,Botafogo,38,18,18,2,32,24,8,72
3,Ceará,38,16,14,8,26,30,-4,62
4,CSA,38,10,23,5,17,26,-9,53
5,CRB,38,12,15,11,19,21,-2,51
6,Avaí,38,11,17,10,17,16,1,50
7,Remo,38,10,20,8,20,17,3,50
8,Chapecoense,38,9,19,10,17,17,0,46
9,Brasil de Pelotas,38,10,15,13,11,24,-13,45
10,Confiança,38,9,18,11,22,13,9,45
11,Londrina,38,10,13,15,22,23,-1,43
12,Vila Nova,38,7,20,11,11,22,-11,41
13,Sport Recife,38,8,16,14,19,32,-13,40
14,Ponte Preta,38,6,22,10,12,13,-1,40
15,Sampaio Corrêa,38,6,21,11,13,15,-2,39
16,Guarani,38,7,18,13,17,18,-1,39
17,Vitória,38,7,18,13,15,17,-2,39
18,Náutico,38,6,19,13,15,24,-9,37
19,São José,38,0,17,21,10,22,-12,17

In [13]:
pd.DataFrame(serie_b_25, columns=header)

,Clube,Partidas,Vitorias,Empates,Derrotas,Gols Marcados,Gols Sofridos,Saldo de Gols,Pontos
0,Atlético Goianiense,38,23,11,4,29,31,-2,80
1,Coritiba,38,18,19,1,23,23,0,73
2,Brusque,38,13,20,5,14,22,-8,59
3,CSA,38,15,14,9,25,14,11,59
4,Sport Recife,38,13,17,8,15,26,-11,56
5,Confiança,38,12,18,8,15,16,-1,54
6,Remo,38,12,17,9,12,14,-2,53
7,Ponte Preta,38,10,23,5,16,9,7,53
8,Brasil de Pelotas,38,11,17,10,20,15,5,50
9,Avaí,38,8,22,8,15,14,1,46
10,Juventude,38,8,21,9,23,17,6,45
11,Sampaio Corrêa,38,9,18,11,19,23,-4,45
12,Londrina,38,9,16,13,15,17,-2,43
13,Operário,38,7,21,10,24,9,15,42
14,Vila Nova,38,6,22,10,24,17,7,40
15,Chapecoense,38,6,18,14,9,16,-7,36
16,CRB,38,6,18,14,19,22,-3,36
17,Santa Cruz,38,3,20,15,14,9,5,29
18,Oeste,38,3,20,15,10,13,-3,29
19,Novorizontino,38,4,16,18,15,15,0,28

In [14]:
# Serie C

serie_c_22 = championships_controller.select_championship_table_by_division(2022, 'Serie C')
serie_c_23 = championships_controller.select_championship_table_by_division(2023, 'Serie C')
serie_c_24 = championships_controller.select_championship_table_by_division(2024, 'Serie C')
serie_c_25 = championships_controller.select_championship_table_by_division(2025, 'Serie C')

In [15]:
pd.DataFrame(serie_c_22, columns=header)

,Clube,Partidas,Vitorias,Empates,Derrotas,Gols Marcados,Gols Sofridos,Saldo de Gols,Pontos
0,Novorizontino,38,11,23,4,5,11,-6,56
1,São José,38,9,25,4,10,9,1,52
2,Mirasol,38,9,23,6,8,16,-8,50
3,Jacuipense,38,8,26,4,9,6,3,50
4,Santa Cruz,38,9,23,6,13,9,4,50
5,Floresta,38,7,28,3,6,8,-2,49
6,Ypiranga,38,10,19,9,11,14,-3,49
7,Manaus,38,8,22,8,11,5,6,46
8,Volta Redonda,38,7,25,6,8,10,-2,46
9,Altos,38,7,24,7,10,7,3,45
10,Botafogo-PB,38,5,29,4,5,6,-1,44
11,Tombense,38,6,25,7,12,6,6,43
12,Ferroviário,38,5,26,7,5,8,-3,41
13,Paraná,38,6,23,9,11,5,6,41
14,Paysandu,38,4,28,6,8,4,4,40
15,Figueirense,38,4,27,7,12,7,5,39
16,Botafogo SP,38,4,27,7,8,8,0,39
17,Criciúma,38,4,26,8,9,7,2,38
18,Oeste,38,5,23,10,11,9,2,38
19,Ituano,38,3,26,9,6,13,-7,35

In [16]:
pd.DataFrame(serie_c_23, columns=header)

,Clube,Partidas,Vitorias,Empates,Derrotas,Gols Marcados,Gols Sofridos,Saldo de Gols,Pontos
0,CSA,38,18,14,6,17,18,-1,68
1,Ponte Preta,38,15,18,5,12,17,-5,63
2,Vila Nova,38,13,21,4,12,11,1,60
3,Vitória,38,11,23,4,13,10,3,56
4,Altos,38,11,23,4,7,13,-6,56
5,Criciúma,38,9,21,8,12,11,1,48
6,Paysandu,38,8,24,6,11,9,2,48
7,Botafogo-PB,38,6,26,6,11,7,4,44
8,Santa Cruz,38,7,23,8,9,11,-2,44
9,Floresta,38,5,26,7,12,8,4,41
10,Figueirense,38,4,29,5,8,3,5,41
11,Ituano,38,6,22,10,13,6,7,40
12,Ferroviário,38,5,24,9,8,11,-3,39
13,Paraná,38,4,27,7,8,8,0,39
14,Manaus,38,4,26,8,9,10,-1,38
15,Ypiranga,38,4,26,8,9,8,1,38
16,Tombense,38,5,22,11,9,12,-3,37
17,Oeste,38,3,27,8,3,8,-5,36
18,Volta Redonda,38,3,26,9,9,10,-1,35
19,Botafogo SP,38,3,24,11,8,13,-5,33

In [17]:
pd.DataFrame(serie_c_24, columns=header)

,Clube,Partidas,Vitorias,Empates,Derrotas,Gols Marcados,Gols Sofridos,Saldo de Gols,Pontos
0,Operário,38,15,22,1,11,13,-2,67
1,Santa Cruz,38,11,23,4,11,10,1,56
2,Novorizontino,38,11,19,8,14,13,1,52
3,Oeste,38,9,24,5,8,12,-4,51
4,Ypiranga,38,10,21,7,10,12,-2,51
5,Botafogo-PB,38,9,22,7,11,12,-1,49
6,Paraná,38,8,22,8,11,11,0,46
7,Volta Redonda,38,5,30,3,6,4,2,45
8,Floresta,38,5,29,4,5,9,-4,44
9,Figueirense,38,7,22,9,9,19,-10,43
10,Mirasol,38,6,25,7,9,8,1,43
11,Ituano,38,4,29,5,5,8,-3,41
12,Paysandu,38,6,23,9,10,8,2,41
13,Tombense,38,7,20,11,12,14,-2,41
14,Criciúma,38,3,31,4,7,1,6,40
15,Ferroviário,38,5,23,10,12,5,7,38
16,Jacuipense,38,4,26,8,6,8,-2,38
17,Manaus,38,4,25,9,9,5,4,37
18,Botafogo SP,38,2,31,5,11,5,6,37
19,Altos,38,4,23,11,9,7,2,35

In [18]:
pd.DataFrame(serie_c_25, columns=header)

,Clube,Partidas,Vitorias,Empates,Derrotas,Gols Marcados,Gols Sofridos,Saldo de Gols,Pontos
0,Vitória,38,15,19,4,15,11,4,64
1,Guarani,38,14,19,5,20,8,12,61
2,Náutico,38,12,20,6,11,13,-2,56
3,Ypiranga,38,12,19,7,11,10,1,55
4,Altos,38,9,22,7,10,8,2,49
5,Floresta,38,8,24,6,11,6,5,48
6,Botafogo-PB,38,8,22,8,9,7,2,46
7,Paraná,38,7,23,8,10,10,0,44
8,Figueirense,38,4,31,3,9,8,1,43
9,Mirasol,38,7,22,9,11,9,2,43
10,Paysandu,38,5,27,6,12,6,6,42
11,Tombense,38,5,26,7,5,9,-4,41
12,Manaus,38,4,29,5,9,3,6,41
13,Botafogo SP,38,4,29,5,9,4,5,41
14,Ferroviário,38,5,25,8,13,3,10,40
15,São José,38,3,29,6,10,7,3,38
16,Ituano,38,3,28,7,8,5,3,37
17,Volta Redonda,38,3,27,8,4,11,-7,36
18,Criciúma,38,4,24,10,8,8,0,36
19,Jacuipense,38,1,29,8,5,4,1,32

In [19]:
"""
Analisando as tabelas é necessario aplicar um meio de padronizar o 'poder de fogo' dos clubs maiores
e manter uma constrancia nos clubes para que consiga trazer mais riqueza aos dados

Regulando a qualidade dos jogadores que atuam já pode ser uma maneira de se regularizar esses dados
pois aparente os clubes que divisoes inferiores tendem a ser campeao das superiores mesmo que na realidade
as divisoes possuem um peso de excelencia

Passo 1
Atribuir um padrão de criação de dados para jogadores de times grandes e pequenos,
baseados na divisão que eles jogam.
Para isso o confifgure devera puxar os clubes por divisão
e o data generation nao deve criar dados da maneira atual

ex:
configure -> criar jogadores skills por divisão
data_manipulation -> criar dados baseados num peso
"""

"\nAnalisando as tabelas é necessario aplicar um meio de padronizar o 'poder de fogo' dos clubs maiores\ne manter uma constrancia nos clubes para que consiga trazer mais riqueza aos dados\n\nRegulando a qualidade dos jogadores que atuam já pode ser uma maneira de se regularizar esses dados\npois aparente os clubes que divisoes inferiores tendem a ser campeao das superiores mesmo que na realidade\nas divisoes possuem um peso de excelencia\n\nPasso 1\nAtribuir um padrão de criação de dados para jogadores de times grandes e pequenos,\nbaseados na divisão que eles jogam.\nPara isso o confifgure devera puxar os clubes por divisão\ne o data generation nao deve criar dados da maneira atual\n\nex:\nconfigure -> criar jogadores skills por divisão\ndata_manipulation -> criar dados baseados num peso\n"

In [20]:
# 19 dez 2023

"""
Analisando os resultados, conclui-se que:
Time da serie B e da serie C são potencialmente capazes de ganhar a serie A e/ou as series seguintes, como o floresta 
que foi campeao seguida da C, B e depois da A.

O lógico é que essas divisões possuem um nível técnico mais baixo, onde a lógica, se estabeleça de que quando um time caia,
ele tenha mais capacidade de sumir do seguir descendo como ocorreu o são paulo por exemplo, e times da serie B que subam pra A mesmo que possuem um nivel
técnico elevado com relação ao "teto técnico" da serie B não é o suficiente na serie A para que ele já seja capaz de conseguir ganhar a divisão.

Mudanças:
    Atribuir pesos a criação dos jogadores, essa regra de negocio pode ser aplicada dentro da aplicação e não no banco de dados
    Players.skills -> peso_baseado_no_clube

    Isso contando no overall total, porém esses valores podem ser distribuidos nas habilidades já que o que conta em si é a habilidade que 
    está sendo requerida e não o overall como um todo.
    
    A -> Jogadores de 55 a 80
    B -> Jogadores de 55 a 70
    C -> Jogadores de 55 a 65

    As médias de gols marcados é muito baixa, a de gols sofridos parace estar numa média boa, e as divisões também deveriam ter 
    diferenças com relação a quantidade de gols marcados e sofridos, porém essas mudanças talvez já possam ser observadas com as mudanças 
    das skills dos jogadores.
"""

'\nAnalisando os resultados, conclui-se que:\nTime da serie B e da serie C são potencialmente capazes de ganhar a serie A e/ou as series seguintes, como o floresta \nque foi campeao seguida da C, B e depois da A.\n\nO lógico é que essas divisões possuem um nível técnico mais baixo, onde a lógica, se estabeleça de que quando um time caia,\nele tenha mais capacidade de sumir do seguir descendo como ocorreu o são paulo por exemplo, e times da serie B que subam pra A mesmo que possuem um nivel\ntécnico elevado com relação ao "teto técnico" da serie B não é o suficiente na serie A para que ele já seja capaz de conseguir ganhar a divisão.\n\nMudanças:\n    Atribuir pesos a criação dos jogadores, essa regra de negocio pode ser aplicada dentro da aplicação e não no banco de dados\n    Players.skills -> peso_baseado_no_clube\n\n    Isso contando no overall total, porém esses valores podem ser distribuidos nas habilidades já que o que conta em si é a habilidade que \n    está sendo requerida e não o overall como um todo.\n    \n    A -> Jogadores de 55 a 80\n    B -> Jogadores de 55 a 70\n    C -> Jogadores de 55 a 65\n\n    As médias de gols marcados é muito baixa, a de gols sofridos parace estar numa média boa, e as divisões também deveriam ter \n    diferenças com relação a quantidade de gols marcados e sofridos, porém essas mudanças talvez já possam ser observadas com as mudanças \n    das skills dos jogadores.\n'