In [1]:
from db.championships_controller import ChampionshipsController

import pandas as pd

In [2]:
championships_controller = ChampionshipsController()

In [3]:
# Define a header for DataFrame columns

header = ['Clube','Partidas','Vitorias','Empates','Derrotas','Gols Marcados','Gols Sofridos','Saldo de Gols','Pontos']

In [4]:
# Getting season 22 and 23 from champeonato brasileiro serie a

serie_a_22 = championships_controller.select_championship_table_by_division(2022, 'Serie A')
serie_a_23 = championships_controller.select_championship_table_by_division(2023, 'Serie A')

In [5]:
# Define dataframe from serie a 2022

pd.DataFrame(serie_a_22, columns=header)

,Clube,Partidas,Vitorias,Empates,Derrotas,Gols Marcados,Gols Sofridos,Saldo de Gols,Pontos
0,International,38,20,12,6,28,28,0,72
1,Santos,38,18,13,7,40,39,1,67
2,Chapecoense,38,18,12,8,43,44,-1,66
3,Corinthians,38,17,11,10,39,40,-1,62
4,América Mineiro,38,15,13,10,26,32,-6,58
5,Bahia,38,15,13,10,32,30,2,58
6,Ceará,38,15,13,10,25,28,-3,58
7,Grêmio,38,12,18,8,20,25,-5,54
8,Fortaleza,38,9,24,5,22,20,2,51
9,Palmeiras,38,13,12,13,27,37,-10,51
10,Atlético Goianiense,38,12,14,12,24,29,-5,50
11,Flamengo,38,11,13,14,32,41,-9,46
12,Red Bull Bragantino,38,9,16,13,26,42,-16,43
13,São Paulo,38,7,21,10,25,27,-2,42
14,Fluminense,38,9,15,14,25,38,-13,42
15,Sport Recife,38,10,12,16,26,27,-1,42
16,Juventude,38,10,11,17,30,28,2,41
17,Cuiabá,38,7,13,18,37,28,9,34
18,Athletico Paranaense,38,5,16,17,22,27,-5,31
19,Atlético Mineiro,38,6,12,20,33,36,-3,30

In [6]:
# Define dataframe from serie a 2023


pd.DataFrame(serie_a_23, columns=header)

Empty DataFrame
Columns: [Clube, Partidas, Vitorias, Empates, Derrotas, Gols Marcados, Gols Sofridos, Saldo de Gols, Pontos]
Index: []

In [7]:
# Getting season 22 and 23 from champeonato brasileiro serie a

serie_b_22 = championships_controller.select_championship_table_by_division(2022, 'Serie B')
serie_b_23 = championships_controller.select_championship_table_by_division(2023, 'Serie B')

In [8]:
# Define dataframe from serie a 2022

pd.DataFrame(serie_b_22, columns=header)

,Clube,Partidas,Vitorias,Empates,Derrotas,Gols Marcados,Gols Sofridos,Saldo de Gols,Pontos
0,Guarani,38,18,11,9,24,27,-3,65
1,CRB,38,16,16,6,22,22,0,64
2,Náutico,38,16,14,8,39,35,4,62
3,CSA,38,15,14,9,25,29,-4,59
4,Sampaio Corrêa,38,16,10,12,22,34,-12,58
5,Coritiba,38,15,13,10,28,29,-1,58
6,Ponte Preta,38,15,10,13,27,24,3,55
7,Goiás,38,15,10,13,27,28,-1,55
8,Brasil de Pelotas,38,13,15,10,26,24,2,54
9,Botafogo,38,13,14,11,26,25,1,53
10,Cruzeiro,38,13,11,14,27,37,-10,50
11,Vasco da Gama,38,13,10,15,38,31,7,49
12,Remo,38,9,19,10,30,24,6,46
13,Avaí,38,10,15,13,19,24,-5,45
14,Vila Nova,38,10,12,16,33,25,8,42
15,Brusque,38,10,11,17,23,38,-15,41
16,Operário,38,9,13,16,30,38,-8,40
17,Vitória,38,9,12,17,31,42,-11,39
18,Londrina,38,4,23,11,19,19,0,35
19,Confiança,38,5,19,14,18,21,-3,34

In [9]:
# Define dataframe from serie a 2023

pd.DataFrame(serie_b_23, columns=header)

Empty DataFrame
Columns: [Clube, Partidas, Vitorias, Empates, Derrotas, Gols Marcados, Gols Sofridos, Saldo de Gols, Pontos]
Index: []

In [10]:
"""
Analisando as tabelas é necessario aplicar um meio de padronizar o 'poder de fogo' dos clubs maiores
e manter uma constrancia nos clubes para que consiga trazer mais riqueza aos dados

Regulando a qualidade dos jogadores que atuam já pode ser uma maneira de se regularizar esses dados
pois aparente os clubes que divisoes inferiores tendem a ser campeao das superiores mesmo que na realidade
as divisoes possuem um peso de excelencia

Passo 1
Atribuir um padrão de criação de dados para jogadores de times grandes e pequenos,
baseados na divisão que eles jogam.
Para isso o confifgure devera puxar os clubes por divisão
e o data generation nao deve criar dados da maneira atual

ex:
configure -> criar jogadores skills por divisão
data_manipulation -> criar dados baseados num peso
"""

"\nAnalisando as tabelas é necessario aplicar um meio de padronizar o 'poder de fogo' dos clubs maiores\ne manter uma constrancia nos clubes para que consiga trazer mais riqueza aos dados\n\nRegulando a qualidade dos jogadores que atuam já pode ser uma maneira de se regularizar esses dados\npois aparente os clubes que divisoes inferiores tendem a ser campeao das superiores mesmo que na realidade\nas divisoes possuem um peso de excelencia\n\nPasso 1\nAtribuir um padrão de criação de dados para jogadores de times grandes e pequenos,\nbaseados na divisão que eles jogam.\nPara isso o confifgure devera puxar os clubes por divisão\ne o data generation nao deve criar dados da maneira atual\n\nex:\nconfigure -> criar jogadores skills por divisão\ndata_manipulation -> criar dados baseados num peso\n"