In [1]:
from controllers.championships_controller import ChampionshipsController

import pandas as pd

In [2]:
championships_controller = ChampionshipsController()

In [3]:
# Define a header for DataFrame columns

header = ['Clube','Partidas','Vitorias','Empates','Derrotas','Gols Marcados','Gols Sofridos','Saldo de Gols','Pontos']

In [4]:
# Getting season 22 and 23 from champeonato brasileiro serie a

serie_a_22 = championships_controller.select_championship_table_by_division(2022, 'Serie A')
serie_a_23 = championships_controller.select_championship_table_by_division(2023, 'Serie A')
serie_a_24 = championships_controller.select_championship_table_by_division(2024, 'Serie A')
serie_a_25 = championships_controller.select_championship_table_by_division(2025, 'Serie A')

In [5]:
# Define dataframe from serie a 2022

pd.DataFrame(serie_a_22, columns=header)

,Clube,Partidas,Vitorias,Empates,Derrotas,Gols Marcados,Gols Sofridos,Saldo de Gols,Pontos
0,Grêmio,38,26,5,7,74,74,0,83
1,International,38,25,3,10,80,62,18,78
2,Palmeiras,38,22,8,8,72,58,14,74
3,São Paulo,38,23,5,10,62,85,-23,74
4,Corinthians,38,21,5,12,63,61,2,68
5,Fluminense,38,19,10,9,58,53,5,67
6,Atlético Mineiro,38,19,9,10,72,70,2,66
7,Flamengo,38,16,6,16,51,75,-24,54
8,Athletico Paranaense,38,13,10,15,51,48,3,49
9,Atlético Goianiense,38,14,5,19,54,45,9,47
10,Bahia,38,12,11,15,55,44,11,47
11,Fortaleza,38,13,7,18,53,43,10,46
12,Santos,38,12,9,17,45,51,-6,45
13,América Mineiro,38,12,9,17,51,48,3,45
14,Red Bull Bragantino,38,12,8,18,60,51,9,44
15,Cuiabá,38,9,11,18,60,61,-1,38
16,Sport Recife,38,10,8,20,47,53,-6,38
17,Juventude,38,9,8,21,46,52,-6,35
18,Chapecoense,38,7,11,20,56,41,15,32
19,Ceará,38,7,10,21,54,41,13,31

In [6]:
# Define dataframe from serie a 2023


pd.DataFrame(serie_a_23, columns=header)

,Clube,Partidas,Vitorias,Empates,Derrotas,Gols Marcados,Gols Sofridos,Saldo de Gols,Pontos
0,Corinthians,38,26,6,6,67,57,10,84
1,Grêmio,38,26,3,9,84,67,17,81
2,Fluminense,38,24,6,8,79,86,-7,78
3,International,38,21,9,8,72,70,2,72
4,Atlético Mineiro,38,21,5,12,68,75,-7,68
5,Flamengo,38,19,7,12,72,64,8,64
6,Palmeiras,38,17,12,9,81,69,12,63
7,São Paulo,38,17,9,12,54,71,-17,60
8,Fortaleza,38,13,9,16,60,44,16,48
9,Cruzeiro,38,13,9,16,55,46,9,48
10,Athletico Paranaense,38,12,11,15,67,52,15,47
11,Red Bull Bragantino,38,11,12,15,55,50,5,45
12,América Mineiro,38,11,10,17,48,58,-10,43
13,Santos,38,10,10,18,54,43,11,40
14,Botafogo,38,9,11,18,66,47,19,38
15,Bahia,38,9,10,19,47,63,-16,37
16,Cuiabá,38,9,10,19,62,64,-2,37
17,Coritiba,38,8,12,18,43,55,-12,36
18,Atlético Goianiense,38,10,6,22,62,67,-5,36
19,Vila Nova,38,7,7,24,54,44,10,28

In [7]:
pd.DataFrame(serie_a_24, columns=header)

,Clube,Partidas,Vitorias,Empates,Derrotas,Gols Marcados,Gols Sofridos,Saldo de Gols,Pontos
0,Palmeiras,38,24,5,9,57,63,-6,77
1,Flamengo,38,22,10,6,60,60,0,76
2,São Paulo,38,23,7,8,70,68,2,76
3,Corinthians,38,22,6,10,73,69,4,72
4,Atlético Mineiro,38,20,8,10,60,70,-10,68
5,Grêmio,38,18,10,10,68,70,-2,64
6,Fluminense,38,18,8,12,66,53,13,62
7,International,38,17,7,14,69,67,2,58
8,América Mineiro,38,16,6,16,42,54,-12,54
9,Cruzeiro,38,14,9,15,45,51,-6,51
10,Fortaleza,38,12,8,18,55,59,-4,44
11,Santos,38,12,8,18,54,54,0,44
12,Athletico Paranaense,38,11,10,17,55,46,9,43
13,Ceará,38,10,13,15,53,52,1,43
14,Bahia,38,11,10,17,50,54,-4,43
15,Goiás,38,11,9,18,60,51,9,42
16,CRB,38,8,14,16,44,45,-1,38
17,Botafogo,38,10,7,21,63,54,9,37
18,Red Bull Bragantino,38,10,6,22,51,59,-8,36
19,Juventude,38,7,7,24,43,49,-6,28

In [8]:
pd.DataFrame(serie_a_25, columns=header)

Empty DataFrame
Columns: [Clube, Partidas, Vitorias, Empates, Derrotas, Gols Marcados, Gols Sofridos, Saldo de Gols, Pontos]
Index: []

In [9]:
# Getting season 22 and 23 from champeonato brasileiro serie a

serie_b_22 = championships_controller.select_championship_table_by_division(2022, 'Serie B')
serie_b_23 = championships_controller.select_championship_table_by_division(2023, 'Serie B')
serie_b_24 = championships_controller.select_championship_table_by_division(2024, 'Serie B')
serie_b_25 = championships_controller.select_championship_table_by_division(2025, 'Serie B')

In [10]:
# Define dataframe from serie a 2022

pd.DataFrame(serie_b_22, columns=header)

,Clube,Partidas,Vitorias,Empates,Derrotas,Gols Marcados,Gols Sofridos,Saldo de Gols,Pontos
0,Cruzeiro,38,22,8,8,47,52,-5,74
1,Coritiba,38,20,7,11,40,36,4,67
2,Botafogo,38,19,8,11,32,50,-18,65
3,Vila Nova,38,18,11,9,37,44,-7,65
4,Goiás,38,18,10,10,40,43,-3,64
5,Confiança,38,15,10,13,37,45,-8,55
6,Avaí,38,15,9,14,41,41,0,54
7,Vasco da Gama,38,13,10,15,54,45,9,49
8,Brasil de Pelotas,38,12,12,14,47,37,10,48
9,CRB,38,11,15,12,27,41,-14,48
10,Guarani,38,12,11,15,30,38,-8,47
11,Operário,38,12,11,15,38,36,2,47
12,Brusque,38,11,13,14,43,34,9,46
13,Vitória,38,12,10,16,36,34,2,46
14,Remo,38,9,18,11,34,37,-3,45
15,Ponte Preta,38,13,5,20,42,36,6,44
16,Sampaio Corrêa,38,10,13,15,33,36,-3,43
17,Londrina,38,10,12,16,43,34,9,42
18,CSA,38,8,16,14,35,25,10,40
19,Náutico,38,8,15,15,38,38,0,39

In [11]:
# Define dataframe from serie a 2023

pd.DataFrame(serie_b_23, columns=header)

,Clube,Partidas,Vitorias,Empates,Derrotas,Gols Marcados,Gols Sofridos,Saldo de Gols,Pontos
0,Goiás,38,22,10,6,49,34,15,76
1,CRB,38,19,10,9,35,26,9,67
2,Ceará,38,20,6,12,38,55,-17,66
3,Juventude,38,17,13,8,27,32,-5,64
4,Avaí,38,16,16,6,42,46,-4,64
5,Brasil de Pelotas,38,15,15,8,34,30,4,60
6,Sport Recife,38,16,11,11,29,53,-24,59
7,Confiança,38,15,13,10,40,25,15,58
8,Vitória,38,16,9,13,28,28,0,57
9,Vasco da Gama,38,13,13,12,38,46,-8,52
10,Brusque,38,14,10,14,39,35,4,52
11,Ponte Preta,38,12,15,11,38,36,2,51
12,Remo,38,13,9,16,37,31,6,48
13,Operário,38,12,11,15,31,25,6,47
14,Guarani,38,10,13,15,22,40,-18,43
15,Chapecoense,38,8,14,16,39,32,7,38
16,Volta Redonda,38,7,16,15,11,30,-19,37
17,Oeste,38,8,12,18,26,20,6,36
18,Jacuipense,38,2,19,17,14,29,-15,25
19,Tombense,38,2,11,25,31,23,8,17

In [12]:
pd.DataFrame(serie_b_24, columns=header)

,Clube,Partidas,Vitorias,Empates,Derrotas,Gols Marcados,Gols Sofridos,Saldo de Gols,Pontos
0,Vasco da Gama,38,22,9,7,49,44,5,75
1,Atlético Goianiense,38,20,9,9,50,40,10,69
2,Cuiabá,38,17,13,8,42,41,1,64
3,Sport Recife,38,16,11,11,40,33,7,59
4,Sampaio Corrêa,38,15,13,10,36,32,4,58
5,Coritiba,38,15,12,11,44,43,1,57
6,Londrina,38,17,5,16,33,33,0,56
7,Vitória,38,13,15,10,41,38,3,54
8,Brasil de Pelotas,38,14,10,14,35,31,4,52
9,Náutico,38,14,10,14,35,32,3,52
10,Chapecoense,38,13,12,13,31,35,-4,51
11,CSA,38,11,14,13,33,43,-10,47
12,Ponte Preta,38,12,11,15,36,39,-3,47
13,Remo,38,11,13,14,36,38,-2,46
14,Guarani,38,10,12,16,33,49,-16,42
15,Operário,38,8,17,13,49,30,19,41
16,Avaí,38,11,8,19,42,39,3,41
17,Confiança,38,9,13,16,30,31,-1,40
18,Brusque,38,8,13,17,38,23,15,37
19,Vila Nova,38,9,10,19,29,44,-15,37

In [13]:
pd.DataFrame(serie_b_25, columns=header)

Empty DataFrame
Columns: [Clube, Partidas, Vitorias, Empates, Derrotas, Gols Marcados, Gols Sofridos, Saldo de Gols, Pontos]
Index: []

In [14]:
# Serie C

serie_c_22 = championships_controller.select_championship_table_by_division(2022, 'Serie C')
serie_c_23 = championships_controller.select_championship_table_by_division(2023, 'Serie C')
serie_c_24 = championships_controller.select_championship_table_by_division(2024, 'Serie C')
serie_c_25 = championships_controller.select_championship_table_by_division(2025, 'Serie C')

In [15]:
pd.DataFrame(serie_c_22, columns=header)

,Clube,Partidas,Vitorias,Empates,Derrotas,Gols Marcados,Gols Sofridos,Saldo de Gols,Pontos
0,Volta Redonda,38,14,19,5,18,13,5,61
1,Oeste,38,14,14,10,18,22,-4,56
2,Jacuipense,38,13,16,9,22,12,10,55
3,Tombense,38,11,20,7,15,18,-3,53
4,Ferroviário,38,12,16,10,21,15,6,52
5,São José,38,11,19,8,12,15,-3,52
6,Paraná,38,10,22,6,17,15,2,52
7,Novorizontino,38,10,20,8,19,18,1,50
8,Criciúma,38,10,20,8,16,22,-6,50
9,Botafogo-PB,38,10,19,9,20,22,-2,49
10,Altos,38,9,20,9,12,12,0,47
11,Ituano,38,9,19,10,17,13,4,46
12,Botafogo SP,38,10,16,12,20,12,8,46
13,Mirasol,38,8,20,10,14,19,-5,44
14,Floresta,38,7,22,9,14,9,5,43
15,Paysandu,38,9,16,13,27,12,15,43
16,Manaus,38,7,20,11,16,10,6,41
17,Figueirense,38,10,11,17,22,18,4,41
18,Santa Cruz,38,7,18,13,17,20,-3,39
19,Ypiranga,38,6,19,13,21,17,4,37

In [16]:
pd.DataFrame(serie_c_23, columns=header)

,Clube,Partidas,Vitorias,Empates,Derrotas,Gols Marcados,Gols Sofridos,Saldo de Gols,Pontos
0,Londrina,38,22,13,3,35,19,16,79
1,Náutico,38,21,11,6,26,24,2,74
2,Sampaio Corrêa,38,20,11,7,23,32,-9,71
3,CSA,38,18,14,6,32,20,12,68
4,Altos,38,10,19,9,17,17,0,49
5,São José,38,10,18,10,23,15,8,48
6,Botafogo-PB,38,9,21,8,10,20,-10,48
7,Floresta,38,9,20,9,15,14,1,47
8,Ituano,38,9,18,11,18,18,0,45
9,Santa Cruz,38,7,23,8,19,17,2,44
10,Ypiranga,38,8,19,11,15,23,-8,43
11,Botafogo SP,38,7,21,10,14,23,-9,42
12,Paysandu,38,7,21,10,23,17,6,42
13,Manaus,38,8,18,12,18,16,2,42
14,Novorizontino,38,7,18,13,21,23,-2,39
15,Figueirense,38,6,20,12,21,14,7,38
16,Ferroviário,38,5,21,12,23,20,3,36
17,Mirasol,38,7,15,16,29,20,9,36
18,Criciúma,38,5,20,13,13,15,-2,35
19,Paraná,38,5,19,14,21,19,2,34

In [17]:
pd.DataFrame(serie_c_24, columns=header)

,Clube,Partidas,Vitorias,Empates,Derrotas,Gols Marcados,Gols Sofridos,Saldo de Gols,Pontos
0,Paraná,38,16,16,6,16,29,-13,64
1,Floresta,38,15,11,12,21,24,-3,56
2,Botafogo-PB,38,11,21,6,21,15,6,54
3,Santa Cruz,38,10,24,4,8,15,-7,54
4,Paysandu,38,12,18,8,17,15,2,54
5,Jacuipense,38,12,15,11,23,23,0,51
6,São José,38,9,22,7,10,17,-7,49
7,Manaus,38,11,16,11,20,20,0,49
8,Mirasol,38,9,21,8,13,16,-3,48
9,Figueirense,38,10,18,10,14,20,-6,48
10,Criciúma,38,8,22,8,18,18,0,46
11,Ituano,38,8,21,9,14,14,0,45
12,Volta Redonda,38,9,17,12,16,18,-2,44
13,Botafogo SP,38,9,17,12,17,15,2,44
14,Ferroviário,38,7,22,9,12,21,-9,43
15,Ypiranga,38,8,18,12,11,21,-10,42
16,Tombense,38,8,18,12,19,14,5,42
17,Altos,38,8,17,13,16,21,-5,41
18,Novorizontino,38,6,22,10,21,20,1,40
19,Oeste,38,7,18,13,21,18,3,39

In [18]:
pd.DataFrame(serie_c_25, columns=header)

Empty DataFrame
Columns: [Clube, Partidas, Vitorias, Empates, Derrotas, Gols Marcados, Gols Sofridos, Saldo de Gols, Pontos]
Index: []

In [19]:
"""
Analisando as tabelas é necessario aplicar um meio de padronizar o 'poder de fogo' dos clubs maiores
e manter uma constrancia nos clubes para que consiga trazer mais riqueza aos dados

Regulando a qualidade dos jogadores que atuam já pode ser uma maneira de se regularizar esses dados
pois aparente os clubes que divisoes inferiores tendem a ser campeao das superiores mesmo que na realidade
as divisoes possuem um peso de excelencia

Passo 1
Atribuir um padrão de criação de dados para jogadores de times grandes e pequenos,
baseados na divisão que eles jogam.
Para isso o confifgure devera puxar os clubes por divisão
e o data generation nao deve criar dados da maneira atual

ex:
configure -> criar jogadores skills por divisão
data_manipulation -> criar dados baseados num peso
"""

"\nAnalisando as tabelas é necessario aplicar um meio de padronizar o 'poder de fogo' dos clubs maiores\ne manter uma constrancia nos clubes para que consiga trazer mais riqueza aos dados\n\nRegulando a qualidade dos jogadores que atuam já pode ser uma maneira de se regularizar esses dados\npois aparente os clubes que divisoes inferiores tendem a ser campeao das superiores mesmo que na realidade\nas divisoes possuem um peso de excelencia\n\nPasso 1\nAtribuir um padrão de criação de dados para jogadores de times grandes e pequenos,\nbaseados na divisão que eles jogam.\nPara isso o confifgure devera puxar os clubes por divisão\ne o data generation nao deve criar dados da maneira atual\n\nex:\nconfigure -> criar jogadores skills por divisão\ndata_manipulation -> criar dados baseados num peso\n"

In [20]:
# 19 dez 2023

"""
Analisando os resultados, conclui-se que:
Time da serie B e da serie C são potencialmente capazes de ganhar a serie A e/ou as series seguintes, como o floresta 
que foi campeao seguida da C, B e depois da A.

O lógico é que essas divisões possuem um nível técnico mais baixo, onde a lógica, se estabeleça de que quando um time caia,
ele tenha mais capacidade de sumir do seguir descendo como ocorreu o são paulo por exemplo, e times da serie B que subam pra A mesmo que possuem um nivel
técnico elevado com relação ao "teto técnico" da serie B não é o suficiente na serie A para que ele já seja capaz de conseguir ganhar a divisão.

Mudanças:
    Atribuir pesos a criação dos jogadores, essa regra de negocio pode ser aplicada dentro da aplicação e não no banco de dados
    Players.skills -> peso_baseado_no_clube

    Isso contando no overall total, porém esses valores podem ser distribuidos nas habilidades já que o que conta em si é a habilidade que 
    está sendo requerida e não o overall como um todo.
    
    A -> Jogadores de 55 a 80
    B -> Jogadores de 55 a 70
    C -> Jogadores de 55 a 65

    As médias de gols marcados é muito baixa, a de gols sofridos parace estar numa média boa, e as divisões também deveriam ter 
    diferenças com relação a quantidade de gols marcados e sofridos, porém essas mudanças talvez já possam ser observadas com as mudanças 
    das skills dos jogadores.
"""

'\nAnalisando os resultados, conclui-se que:\nTime da serie B e da serie C são potencialmente capazes de ganhar a serie A e/ou as series seguintes, como o floresta \nque foi campeao seguida da C, B e depois da A.\n\nO lógico é que essas divisões possuem um nível técnico mais baixo, onde a lógica, se estabeleça de que quando um time caia,\nele tenha mais capacidade de sumir do seguir descendo como ocorreu o são paulo por exemplo, e times da serie B que subam pra A mesmo que possuem um nivel\ntécnico elevado com relação ao "teto técnico" da serie B não é o suficiente na serie A para que ele já seja capaz de conseguir ganhar a divisão.\n\nMudanças:\n    Atribuir pesos a criação dos jogadores, essa regra de negocio pode ser aplicada dentro da aplicação e não no banco de dados\n    Players.skills -> peso_baseado_no_clube\n\n    Isso contando no overall total, porém esses valores podem ser distribuidos nas habilidades já que o que conta em si é a habilidade que \n    está sendo requerida e não o overall como um todo.\n    \n    A -> Jogadores de 55 a 80\n    B -> Jogadores de 55 a 70\n    C -> Jogadores de 55 a 65\n\n    As médias de gols marcados é muito baixa, a de gols sofridos parace estar numa média boa, e as divisões também deveriam ter \n    diferenças com relação a quantidade de gols marcados e sofridos, porém essas mudanças talvez já possam ser observadas com as mudanças \n    das skills dos jogadores.\n'